name: 'Setup AMXXPawn Compiler'
author: 'wopox1337'
description: 'Install and setup AMXXPawn compiler'
inputs:
  version:
    description: 'Version of AMXXPawn compiler'
    required: true
    default: '1.9.x'
  version-file:
    description: 'File to parse to get the version of the plugin'
    required: false
    default: ''
  define-name:
    description: 'Name of the define for the version of the plugin if you are using one'
    required: false
    default: ''
outputs:
  version:
    description: 'Version of the AMXXPawn compiler used'
  version-file:
    description: 'Version of the .sma file'
runs:
  using: 'node20'
  main: 'lib/index.js'
branding:
  icon: 'command'  
  color: 'blue'